"""Add models for the new apps added

Revision ID: ef643bffcad0
Revises: 9041aa0758f8
Create Date: 2024-06-19 18:38:26.131804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef643bffcad0'
down_revision = '9041aa0758f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_schedules', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('scheduled', 'completed', name='schedulestatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_schedules', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('scheduled', 'completed', name='schedulestatus'),
               type_=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
